language: node_js

node_js:
  - "node"

addons:
  apt:
    packages:
      - libgconf-2-4

cache:
  npm: true
  directories:
    - ~/.cache

before_install: cd frontend

before_script:
  - npm test && npm run dev &

script:
  - npm run cy:run
