language: node_js
node_js:
  - "node"
before_install: cd frontend
script:
  - $(npm bin)/print-env TRAVIS
  - npm run dev -- --silent &
  - npm run cy:run -- --parallel --group $STAGE_NAME
  - kill $(jobs -p) || true
cache:
  directories:
    - ~/.npm
    - ~/.cache
  override:
    - npm ci
    - npm run cy:verify
